### ISSUE TITLE
There is no system details about benchmark system

### ISSUE THREAD

**Issue by rahmanusta** [aliemrahpekesen/mappers-benchmark#2]
Could you please share your system details about test environment.
- OS version
- CPU architecture
- Java version detail

**Comment by aliemrahpekesen** [comment]
Please be informed that system details of test envirnment is added in readme file. If it is OK with you could you please let me know to close this issue?

**Comment by rahmanusta** [comment]
Yes, it is okay guy. Thanks for giving this informations.
